config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'
  
  get 'hashtags/create'
  get 'hashtags/destroy'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  get 'hashtags/index'
  post 'hashtags/index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  resources :users
  
  
  resources :hashtags, only: [:create, :destroy, :show] 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
    belongs_to :user 
    
    validates :content, presence: true, length: { maximum: 30 }, uniqueness: { scope: :user_id }
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum: 50 }
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }

    has_secure_password
    has_many :hashtags, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:destroy]
  
  def create
    @hashtag = current_user.hashtags.build(hashtag_params)
    if @hashtag.save
      redirect_to root_url
    else
      @hashtags = current_user.hashtags.order(id: :desc)
      flash[:danger] = 'Please input tag using more than one character but less than 30 characters. No blank and no duplicate tag.'
      redirect_to root_url
    end
  end

  def destroy
    @hashtag.destroy
    redirect_back(fallback_location: root_path)
  end

  def show
  end

  private

  def hashtag_params
    params.require(:hashtag).permit(:content)
  end
  
  def randomtag_params
    params.require(:randomtag).permit(:content)
  end

  def correct_user
    @hashtag = current_user.hashtags.find_by(id: params[:id])
    unless @hashtag
      redirect_to root_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'Loged in!'
      redirect_to root_url
    else
      flash.now[:danger] = 'Failed login'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'Loged out'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      session[:user_id] = @user.id
      return true
    else
      return false
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:index, :show]
  before_action :correct_user,   only: [:edit, :update]
  
  def index
    if logged_in?
      @hashtag = current_user.hashtags.build  
      @hashtags = current_user.hashtags.order(id: :desc)
      if params[:hashtag].nil?
        rand = Rails.env.production? ? "RANDOM()" : "rand()"
        @randomtags = current_user.hashtags.order(rand).limit(28)
      else
        rand = Rails.env.production? ? "RANDOM()" : "rand()"
        @randomtags = current_user.hashtags.order(rand).limit(params[:hashtag][:hashtags])
      end
    end
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
    flash[:success] = 'Succeeded!'
    redirect_to @user
    else
    flash.now[:danger] = 'Failed'
    render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
      if @user.update_attributes(user_params)
        flash[:success] = "Profile updated"
        redirect_to @user
      else
        render 'edit'
      end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "Succeed to delete an account!"
    redirect_to signup_path
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
  
  def logged_in_user
    unless logged_in?
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
  
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless @user == current_user
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/hashtags/_hashtags.html.erb
<div class="list-unstyled">
  <% hashtags.each do |hashtag| %>
    <div class="hogehoge mb-3">
      <span><%= hashtag.content %></span>
      <% if current_user == hashtag.user %>
        <%= link_to "X", hashtag, method: :delete,  class: 'btn2 btn-danger btn-sm' %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark" style="background-color:#000099;">
    <a class="navbar-brand" href="/">RandomTag</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to 'Tag Page', href="/", class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to 'Signup', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Login', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Randomtag</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>

app/views/randomtags/_randomtags.html.erb
<% @randomtags.each do |randomtag| %>
    <span class ="r">#<%= randomtag.content %></span>
<% end %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <%= render 'users/index' %>
<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to the RandomTag</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-dark' %>
    </div>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update My profile</h1>
<br>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <br>

      <%= f.submit "Save changes", class: "btn btn-dark" %><br>
      <br>
      <br>
      <%= link_to 'Back to my profile', user_path(current_user), class: "btn btn-dark" %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div id="wrapper">
    <div class ="button">
        <button class="clipboard-btn btn1 btn-primary btn-sm" data-clipboard-action="copy" data-clipboard-target="#bar">Copy</button>
    </div>
    <div class ="button2">
        <%= form_with(model: @hashtag, url: root_path, method: :get, local: true) do |f| %>
            <%= f.submit 'RandomTag', class: 'btn1 btn-primary btn-sm' %>    
            <%= f.label :hashtags, "Set Number" %>
            <%= f.select :hashtags, 1.upto(30).map{|i| [i, i]}, class:"form-control" %><br>
        <% end %>
    </div>
</div>

<div class="box2" id="bar">
    <p><%= render 'randomtags/randomtags', randomtags: @randomtags %></p>
</div>

<div class="mytags">
  <div class="mytag">
    <h3>My Tag</h3>
  </div>
  <div class="mytag">
    <%= form_with(model: @hashtag, local: true) do |f| %>
        <div class = "addtag">
            <%= f.submit 'Add Tag'%>
        </div> 
        <div class = "textarea">
            <%= f.text_field :content %>
        </div>    
    <% end %>
  </div>
</div>

<div class="box3">
  <%= render 'hashtags/hashtags', hashtags: @hashtags %>
</div> 

app/views/users/new.html.erb
<div class="text-center">
  <h1>Sign up</h1>
</div>
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= form_with(model: @user, local: true) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
      <div class="form-group">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>
        <%= f.submit 'Sign up', class: 'btn btn-dark btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h2>User Page</h2>
<br>
<br>
<br>
<p>User Name:     </p><p><%= current_user.name %></p><br>
<p>Email:     </p><p><%= current_user.email %></p><br>
<br>
<br>
<br>
<%= link_to 'Update My profile', edit_user_path(current_user), class: "btn btn-dark" %>
<br>
<br>
<%= link_to 'Delete my account', user_path(current_user), method: :delete, "data-confirm" => "Are you sure?", class: "btn btn-outline-danger" %>